name: Sync main to dev

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to fetch all branches

      - name: Create Pull Request from main to dev
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          head: main
          title: "Sync main to dev"
          body: |
            Automated PR to sync changes from `main` to `dev`.
          commit-message: "Sync dev [ci skip]"
          draft: false
