name: Sync main to dev

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Create Pull Request from main to dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base dev --head main --title "Sync dev [ci skip]" --label dev --body "Automated PR to sync changes from 'main' to 'dev'."
          PR_NUMBER=$(gh pr list --base main --head main --json number -q '.[0].number')
          gh pr merge --auto --merge $PR_NUMBER