name: Sync main to dev

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create Pull Request from main to dev
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: "Sync dev [ci skip]"
          body: |
            Automated PR to sync changes from `main` to `dev`.
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: dev
          labels: |
            dev
            refactoring
          delete-branch: false
          draft: false

      - name: Enable auto-merge for PR
        if: steps.cpr.outputs.pull-request-number != ''
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
