name: Sync main to dev

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Create Pull Request from main to dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base dev \
            --head main \
            --title "Sync dev [ci skip]" \
            --label dev \
            --body "Automated PR to sync changes from 'main' to 'dev'."

          PR_NUMBER=$(gh pr view --json number -q '.number')
          MERGEABLE=$(gh pr view --json mergeable -q '.mergeable')

          if [ "$MERGEABLE" != "MERGEABLE" ]; then
            echo "❌ Merge conflict detected in PR #$PR_NUMBER (mergeable=$MERGEABLE)"
            exit 1
          fi

          gh pr merge --auto --merge "$PR_NUMBER"