name: Sync main to dev

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from main to dev
        run: |
          gh pr create \
            --base dev \
            --head main \
            --title "Sync dev [ci skip]" \
            --label dev \
            --body "Automated PR to sync changes from 'main' to 'dev'."

      - name: Fetch PR number and check mergeability
        id: check
        run: |
          PR_JSON=$(gh pr view --head main --base dev --json number,mergeable)
          echo "$PR_JSON" > pr.json

          MERGEABLE=$(echo "$PR_JSON" | jq -r '.mergeable')
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.number')

          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          echo "MERGEABLE=$MERGEABLE" >> "$GITHUB_OUTPUT"

          if [ "$MERGEABLE" != "MERGEABLE" ]; then
            echo "❌ Merge conflict detected in PR #$PR_NUMBER (mergeable=$MERGEABLE)"
            exit 1
          fi

      - name: Auto-merge PR
        run: |
          gh pr merge --auto --merge "${{ steps.check.outputs.PR_NUMBER }}"